##Hyperbolic

In [4]:
##sinh 
import numpy as np
x = np.sinh(np.pi/2)
print(x)
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x1 = np.cosh(arr)
print(x1)

2.3012989023072947
[2.50917848 1.60028686 1.32460909 1.20397209]


In [7]:
##Finding angles
import numpy as np
x = np.arcsinh(1.0)
print(x)
arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

0.881373587019543
[0.10033535 0.20273255 0.54930614]


##Sets

In [8]:
##Create a set
import numpy as np
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]
