##Hyperbolic

In [4]:
##sinh 
import numpy as np
x = np.sinh(np.pi/2)
print(x)
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x1 = np.cosh(arr)
print(x1)

2.3012989023072947
[2.50917848 1.60028686 1.32460909 1.20397209]


In [7]:
##Finding angles
import numpy as np
x = np.arcsinh(1.0)
print(x)
arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

0.881373587019543
[0.10033535 0.20273255 0.54930614]


##Sets

In [9]:
##Create a set
import numpy as np
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [14]:
##Finding union
import numpy as np
arr1 = np.array([1, 2,6,7,8, 3, 4])
arr2 = np.array([3, 4,7,8, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

[1 2 3 4 5 6 7 8]
[3 4 6 7 8]


In [16]:
##Find the difference
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

##Difference
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)
##symmetric difference
newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)


[1 2]
[1 2 5 6]
