---Normal

In [1]:
from numpy import random

x = random.normal(size=(2, 3))

print(x)

[[ 0.33851609 -1.24969509 -0.33744395]
 [ 0.46817781 -1.28483172 -1.56561561]]


In [2]:
from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[ 5.09131692  2.80354012  1.49271737]
 [-0.65806606 -0.87683724  4.23374814]]
