--------Numpy-------------

In [1]:
###1-d Array
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
###2-d Array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[0,1])

[[1 2 3]
 [4 5 6]]
2


In [3]:
###3-d Array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


---------Numpy Slicing------------

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[-3:-1])
print(arr[1:5:2])

[2 3 4 5]
[5 6 7]
[5 6]
[2 4]


In [13]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


----Data type

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [15]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
