# Numpy Function

In [2]:
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
print(a)

[1 2 3]


In [3]:
# ndarray from tuple 
import numpy as np 

x = (1,2,3) 
a = np.asarray(x) 
print(a)

[1 2 3]


In [4]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print(a)

[(1, 2, 3) (4, 5)]


C:\Users\HP\anaconda3\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


In [7]:
# create list object using range function 
import numpy as np 
list = range(5) 
print(list)

range(0, 5)


In [8]:
# obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print(x)

[0. 1. 2. 3. 4.]
