Udemy Numpy

In [16]:
import numpy
n = [[2,4,6],[2,1,5],[4,3,2]]
narray = numpy.array(n)
print(narray)

[[2 4 6]
 [2 1 5]
 [4 3 2]]


In [17]:
import numpy as np
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
import numpy as np
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
import numpy as np
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.random.rand(5)

array([0.83903705, 0.29009381, 0.65561784, 0.19244137, 0.79932286])

In [7]:
np.random.rand(5,5)

array([[0.24286847, 0.77840363, 0.24591399, 0.69449587, 0.23809737],
       [0.97937324, 0.06726868, 0.54143384, 0.97547673, 0.30528949],
       [0.13938897, 0.46534338, 0.94250626, 0.13859958, 0.62471247],
       [0.10156486, 0.0584646 , 0.26814618, 0.04200139, 0.64146005],
       [0.43704534, 0.70991825, 0.38004163, 0.64617303, 0.01089323]])

In [8]:
np.random.randn(4,4)

array([[ 0.8190744 ,  1.15440564, -0.07715765,  1.10526647],
       [ 0.3631954 , -2.19580558, -0.20341181,  0.14563206],
       [-0.60866642, -0.06917519,  0.3816183 , -0.95826069],
       [ 1.28521171, -1.90569193,  0.67096071,  0.10953507]])

In [14]:
arr = np.random.randint(1,100,10)

In [15]:
arr

array([ 5, 65, 58,  8, 22, 91,  3, 41, 45, 57])

In [23]:
arr = arr.reshape(2,5)

In [18]:
arr.max()

91

In [19]:
arr.min()

3

In [21]:
arr.dtype

dtype('int32')

In [24]:
arr.shape

(2, 5)

Indexing and Position

In [26]:
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr1[8]

8

In [29]:
arr1[:5]

array([0, 1, 2, 3, 4])

In [30]:
arr1[1:5]

array([1, 2, 3, 4])

In [31]:
arr1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arra_2d = np.array([[5,5,6],[2,2,4],[1,3,6]])
arra_2d

array([[5, 5, 6],
       [2, 2, 4],
       [1, 3, 6]])

In [33]:
arra_2d[1][2]

4

In [34]:
arra_2d[1]

array([2, 2, 4])

In [37]:
arra_2d[1][:1]

array([2])

In [38]:
arra_2d[1,2]

4

In [40]:
arra_2d[:1,:1]

array([[5]])

In [41]:
arra_2d[:1]

array([[5, 5, 6]])