Udemy Numpy

In [6]:
import numpy
n = [[2,4,6],[2,1,5],[4,3,2]]
narray = numpy.array(n)
print(narray)

[[2 4 6]
 [2 1 5]
 [4 3 2]]


In [13]:
import numpy as np
print(np.arrange(0,11,2))

AttributeError: module 'numpy' has no attribute 'arrange'