Udemy Numpy

In [16]:
import numpy
n = [[2,4,6],[2,1,5],[4,3,2]]
narray = numpy.array(n)
print(narray)

[[2 4 6]
 [2 1 5]
 [4 3 2]]


In [17]:
import numpy as np
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
import numpy as np
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])