###Random logic

In [15]:
from numpy import random

x = random.randint(100)

y=random.randint(100, size=(5))

z=random.randint(50, size = (2,3))
print(x)
print(y)
print(z)

56
[16 97 88 98 80]
[[33 31  9]
 [ 3 34 16]]


In [10]:
from numpy import random

x = random.rand()

print(x)

0.7999779929103804


In [18]:
from numpy import random

x = random.choice([3, 5,5,12,11,9,1, 7, 9], size=(3, 5))

print(x)

[[12  5  3 12  5]
 [ 9  7  5 11  5]
 [ 5 12  7 11  9]]
