##Ufuncs Numpy

In [3]:
##Sum of two arrays
import numpy as np

x = [2,3,4,5]
y = [12,31,4,51]

z = np.add(x,y) ## Sum of two arrays

print(z)

[14 34  8 56]


In [15]:
##Create Function
import numpy as np

def myadd(x, y):
    return x+y

myadd = np.frompyfunc(myadd, 2, 1)####Sum of two addition

print(type(myadd))
print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

<class 'numpy.ufunc'>
[6 8 10 12]


##Arithmetic

In [16]:
## Add
import numpy as np
arr1 = np.array([101,2,3])
arr2 = np.array([101,101,102])

arr3 = np.add(arr1,arr2)

print(arr3)

[202 103 105]
